version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - '1935:1935'
      - '80:80'
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
  auth:
    build: ./auth
    container_name: auth_server

  # client:
  #   build: ./client
  #   container_name: client_server
  #   ports:
  #     - '80:80'
