version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - '1935:1935'
      - '3000:3000'
      # - '80:80'
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
  auth:
    build: ./auth
    container_name: auth_server
  # server:
  #   build: ./
  #   container_name: response_server
